name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  ci:
    name: CI - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]  # ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Install cargo-nextest
      uses: taiki-e/install-action@nextest

    - name: Format
      run: cargo fmt --all -- --check

    - name: Check
      run: cargo check    

    - name: Clippy
      run: cargo clippy -- -D warnings

    - name: Test
      run: cargo nextest run

    - name: Build
      run: cargo build --release

